import { config } from "dotenv";
config();
import mysql from "mysql2/promise";

const url = process.env.DATABASE_URL;
if (!url) { console.error("No DATABASE_URL"); process.exit(1); }

const conn = await mysql.createConnection(url);

const cards = [
  // Paris
  {
    slug: "le-cinq-paris-george-v",
    title: "Le Cinq — George V",
    subtitle: "Haute gastronomie étoilée",
    category: "restaurant",
    city: "Paris",
    country: "France",
    region: "Île-de-France",
    description: "Restaurant trois étoiles Michelin au cœur du Four Seasons George V. Le Chef Christian Le Squer propose une cuisine française d'exception dans un cadre somptueux orné de fleurs fraîches. Menu dégustation à partir de 395€. Réservation indispensable, tenue élégante exigée.",
    highlights: JSON.stringify(["3 étoiles Michelin", "Chef Christian Le Squer", "Cadre Four Seasons", "Cave exceptionnelle 50 000 bouteilles"]),
    metaTitle: "Le Cinq Paris — Restaurant 3 Étoiles Michelin | George V",
    metaDescription: "Découvrez Le Cinq, restaurant gastronomique 3 étoiles Michelin au Four Seasons George V Paris. Cuisine française d'exception par Christian Le Squer.",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
    priceLevel: "luxury",
    tags: JSON.stringify(["gastronomie", "étoilé", "paris", "luxe", "george v"]),
    status: "published",
    generatedBy: "manual",
    rating: "9.8",
  },
  {
    slug: "hotel-plaza-athenee-paris",
    title: "Hôtel Plaza Athénée",
    subtitle: "Palace mythique avenue Montaigne",
    category: "hotel",
    city: "Paris",
    country: "France",
    region: "Île-de-France",
    description: "Palace iconique de l'avenue Montaigne, le Plaza Athénée incarne l'art de vivre parisien depuis 1913. 208 chambres et suites au décor raffiné, restaurant Alain Ducasse, spa Dior, bar Le Relais Plaza. Vue imprenable sur la Tour Eiffel depuis les suites supérieures.",
    highlights: JSON.stringify(["Palace 5 étoiles", "Restaurant Alain Ducasse", "Spa Dior", "Vue Tour Eiffel", "Avenue Montaigne"]),
    metaTitle: "Plaza Athénée Paris — Palace 5 Étoiles Avenue Montaigne",
    metaDescription: "Réservez au Plaza Athénée, palace légendaire de l'avenue Montaigne à Paris. Spa Dior, restaurant Alain Ducasse, vue Tour Eiffel.",
    imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
    priceLevel: "luxury",
    tags: JSON.stringify(["palace", "paris", "montaigne", "dior", "ducasse"]),
    status: "published",
    generatedBy: "manual",
    rating: "9.7",
  },
  {
    slug: "rooftop-le-perchoir-marais-paris",
    title: "Le Perchoir Marais",
    subtitle: "Rooftop branché avec vue sur Paris",
    category: "rooftop",
    city: "Paris",
    country: "France",
    region: "Île-de-France",
    description: "Perché au 7e étage du BHV Marais, Le Perchoir offre une vue panoramique sur les toits de Paris, de Notre-Dame au Sacré-Cœur. Cocktails signatures, tapas méditerranéennes, ambiance DJ set le week-end. Ouvert d'avril à octobre, réservation recommandée.",
    highlights: JSON.stringify(["Vue 360° sur Paris", "Cocktails signatures", "DJ sets week-end", "Terrasse végétalisée"]),
    metaTitle: "Le Perchoir Marais — Rooftop Paris Vue Panoramique",
    metaDescription: "Le Perchoir Marais, rooftop iconique au cœur de Paris. Vue panoramique, cocktails, DJ sets. Réservez votre soirée.",
    imageUrl: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800",
    priceLevel: "moderate",
    tags: JSON.stringify(["rooftop", "paris", "cocktails", "vue", "marais"]),
    status: "published",
    generatedBy: "manual",
    rating: "8.5",
  },
  // New York
  {
    slug: "eleven-madison-park-nyc",
    title: "Eleven Madison Park",
    subtitle: "Fine dining végétal révolutionnaire",
    category: "restaurant",
    city: "New York",
    country: "États-Unis",
    region: "Manhattan",
    description: "Élu meilleur restaurant du monde en 2017, Eleven Madison Park a révolutionné la haute gastronomie avec son menu 100% végétal. Le Chef Daniel Humm propose un voyage culinaire en 8-10 plats dans un cadre Art Déco face à Madison Square Park. Menu dégustation à partir de $365.",
    highlights: JSON.stringify(["Ex-#1 mondial", "Menu 100% végétal", "Chef Daniel Humm", "Cadre Art Déco", "Madison Square Park"]),
    metaTitle: "Eleven Madison Park NYC — Fine Dining Végétal d'Exception",
    metaDescription: "Eleven Madison Park, restaurant légendaire de New York. Menu végétal révolutionnaire par Daniel Humm face à Madison Square Park.",
    imageUrl: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800",
    priceLevel: "luxury",
    tags: JSON.stringify(["fine dining", "new york", "végétal", "manhattan", "étoilé"]),
    status: "published",
    generatedBy: "manual",
    rating: "9.6",
  },
  {
    slug: "the-peninsula-new-york",
    title: "The Peninsula New York",
    subtitle: "Luxe classique sur la 5e Avenue",
    category: "hotel",
    city: "New York",
    country: "États-Unis",
    region: "Manhattan",
    description: "Situé au cœur de Midtown sur la prestigieuse 5e Avenue, The Peninsula New York allie élégance classique et modernité. 235 chambres, rooftop Salon de Ning avec vue spectaculaire sur Manhattan, spa primé, et service de limousine Rolls-Royce.",
    highlights: JSON.stringify(["5e Avenue", "Rooftop Salon de Ning", "Spa primé", "Rolls-Royce house car", "Vue Manhattan"]),
    metaTitle: "The Peninsula New York — Hôtel de Luxe 5e Avenue Manhattan",
    metaDescription: "The Peninsula New York, hôtel de luxe iconique sur la 5e Avenue. Rooftop, spa, Rolls-Royce, au cœur de Manhattan.",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    priceLevel: "luxury",
    tags: JSON.stringify(["luxe", "new york", "5e avenue", "manhattan", "rooftop"]),
    status: "published",
    generatedBy: "manual",
    rating: "9.5",
  },
  {
    slug: "top-of-the-rock-nyc",
    title: "Top of the Rock",
    subtitle: "Vue panoramique sur Manhattan",
    category: "viewpoint",
    city: "New York",
    country: "États-Unis",
    region: "Manhattan",
    description: "L'observatoire du Rockefeller Center offre la plus belle vue de New York — avec l'Empire State Building en premier plan et Central Park en toile de fond. 3 niveaux d'observation, dont un toit en plein air à 260m. Coucher de soleil recommandé.",
    highlights: JSON.stringify(["Vue Empire State + Central Park", "3 niveaux", "Toit en plein air", "Coucher de soleil spectaculaire"]),
    metaTitle: "Top of the Rock NYC — Meilleure Vue Panoramique Manhattan",
    metaDescription: "Top of the Rock, observatoire du Rockefeller Center. La plus belle vue de New York sur l'Empire State Building et Central Park.",
    imageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800",
    priceLevel: "moderate",
    tags: JSON.stringify(["vue", "new york", "rockefeller", "panorama", "manhattan"]),
    status: "published",
    generatedBy: "manual",
    rating: "9.2",
  },
  // Bali
  {
    slug: "como-shambhala-estate-bali",
    title: "COMO Shambhala Estate",
    subtitle: "Retraite bien-être dans la jungle",
    category: "spa",
    city: "Ubud",
    country: "Indonésie",
    region: "Bali",
    description: "Niché dans la forêt tropicale d'Ubud, COMO Shambhala est un sanctuaire de bien-être holistique. Villas privées avec piscine, programmes de détox et yoga, cuisine Ayurvédique, et soins traditionnels balinais. L'un des meilleurs spas au monde selon Condé Nast Traveler.",
    highlights: JSON.stringify(["Top spa mondial", "Villas jungle privées", "Yoga & méditation", "Cuisine Ayurvédique", "Forêt tropicale Ubud"]),
    metaTitle: "COMO Shambhala Bali — Meilleur Spa & Retraite Bien-Être Ubud",
    metaDescription: "COMO Shambhala Estate, retraite bien-être d'exception à Ubud Bali. Villas jungle, yoga, spa holistique, cuisine Ayurvédique.",
    imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=800",
    priceLevel: "luxury",
    tags: JSON.stringify(["spa", "bali", "ubud", "bien-être", "yoga", "retraite"]),
    status: "published",
    generatedBy: "manual",
    rating: "9.8",
  },
  {
    slug: "potato-head-beach-club-bali",
    title: "Potato Head Beach Club",
    subtitle: "Beach club iconique de Seminyak",
    category: "bar",
    city: "Seminyak",
    country: "Indonésie",
    region: "Bali",
    description: "Le beach club le plus Instagrammable de Bali. Architecture spectaculaire en volets recyclés, piscine infinity face à l'océan, cocktails tropicaux, cuisine fusion, et DJ sets internationaux au coucher du soleil. Entrée gratuite, réservation daybed recommandée.",
    highlights: JSON.stringify(["Architecture iconique", "Piscine infinity océan", "DJ sets sunset", "Cuisine fusion", "Gratuit (hors daybed)"]),
    metaTitle: "Potato Head Beach Club Bali — Beach Club Iconique Seminyak",
    metaDescription: "Potato Head Bali, beach club légendaire de Seminyak. Piscine infinity, cocktails, DJ sets sunset, architecture spectaculaire.",
    imageUrl: "https://images.unsplash.com/photo-1537956965359-7573183d1f57?w=800",
    priceLevel: "upscale",
    tags: JSON.stringify(["beach club", "bali", "seminyak", "sunset", "cocktails"]),
    status: "published",
    generatedBy: "manual",
    rating: "8.9",
  },
  // Alpes
  {
    slug: "cheval-blanc-courchevel",
    title: "Cheval Blanc Courchevel",
    subtitle: "Palace LVMH au sommet des Alpes",
    category: "hotel",
    city: "Courchevel",
    country: "France",
    region: "Alpes",
    description: "Le palace LVMH de Courchevel 1850, ski-in/ski-out sur la piste de la Croisette. 36 chambres et suites signées Sybille de Margerie, restaurant Le 1947 (3 étoiles Michelin par Yannick Alléno), spa Guerlain, et kids club. L'excellence absolue en montagne.",
    highlights: JSON.stringify(["Palace LVMH", "Ski-in/ski-out", "Le 1947 — 3 étoiles Michelin", "Spa Guerlain", "Courchevel 1850"]),
    metaTitle: "Cheval Blanc Courchevel — Palace LVMH Ski-in/Ski-out",
    metaDescription: "Cheval Blanc Courchevel, palace LVMH en ski-in/ski-out. Restaurant 3 étoiles Le 1947, spa Guerlain, au sommet des Alpes.",
    imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    priceLevel: "luxury",
    tags: JSON.stringify(["palace", "courchevel", "ski", "alpes", "lvmh", "étoilé"]),
    status: "published",
    generatedBy: "manual",
    rating: "9.9",
  },
  {
    slug: "la-folie-douce-val-thorens",
    title: "La Folie Douce Val Thorens",
    subtitle: "Fête en altitude à 2600m",
    category: "experience",
    city: "Val Thorens",
    country: "France",
    region: "Alpes",
    description: "Le concept après-ski le plus fou des Alpes. À 2600m d'altitude, La Folie Douce transforme chaque après-midi en festival avec DJ sets, danseurs, et ambiance électrique face au panorama alpin. Restaurant gastronomique La Fruitière au même étage pour les plus gourmands.",
    highlights: JSON.stringify(["2600m d'altitude", "DJ sets quotidiens", "Panorama alpin", "Restaurant La Fruitière", "Ambiance festival"]),
    metaTitle: "La Folie Douce Val Thorens — Après-Ski Légendaire à 2600m",
    metaDescription: "La Folie Douce Val Thorens, l'après-ski le plus fou des Alpes. DJ sets, danseurs, panorama à 2600m d'altitude.",
    imageUrl: "https://images.unsplash.com/photo-1551524559-8af4e6624178?w=800",
    priceLevel: "moderate",
    tags: JSON.stringify(["après-ski", "val thorens", "fête", "alpes", "montagne"]),
    status: "published",
    generatedBy: "manual",
    rating: "8.7",
  },
  // Conciergerie
  {
    slug: "conciergerie-privee-cote-azur",
    title: "Conciergerie Privée Côte d'Azur",
    subtitle: "Service sur-mesure Riviera",
    category: "concierge",
    city: "Nice",
    country: "France",
    region: "Côte d'Azur",
    description: "Service de conciergerie privée dédié à la Côte d'Azur. Organisation complète de séjours : réservation de yachts, tables étoilées, villas privées, transferts hélicoptère, accès VIP aux événements (Festival de Cannes, Grand Prix Monaco). Disponible 24/7.",
    highlights: JSON.stringify(["24/7 disponible", "Yachts & villas", "Accès VIP événements", "Transferts hélicoptère", "Tables étoilées"]),
    metaTitle: "Conciergerie Privée Côte d'Azur — Service Luxe Sur-Mesure",
    metaDescription: "Conciergerie privée Côte d'Azur. Yachts, villas, tables étoilées, VIP Cannes & Monaco. Service sur-mesure 24/7.",
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    priceLevel: "luxury",
    tags: JSON.stringify(["conciergerie", "côte d'azur", "yacht", "vip", "luxe"]),
    status: "published",
    generatedBy: "manual",
    rating: "9.4",
  },
  // Social Club / Mariage
  {
    slug: "soho-house-paris",
    title: "Soho House Paris",
    subtitle: "Club privé créatif",
    category: "experience",
    city: "Paris",
    country: "France",
    region: "Île-de-France",
    description: "Le club privé le plus convoité de Paris, réservé aux membres de l'industrie créative. Rooftop avec vue sur les toits parisiens, piscine, restaurant, salles de projection, et espace de coworking. Membership sur candidature uniquement. Le lieu où se croisent artistes, entrepreneurs et célébrités.",
    highlights: JSON.stringify(["Membres uniquement", "Rooftop & piscine", "Restaurant & bar", "Espace coworking", "Industrie créative"]),
    metaTitle: "Soho House Paris — Club Privé Créatif Exclusif",
    metaDescription: "Soho House Paris, club privé exclusif pour l'industrie créative. Rooftop, piscine, restaurant, au cœur de Paris.",
    imageUrl: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800",
    priceLevel: "luxury",
    tags: JSON.stringify(["club privé", "paris", "social club", "rooftop", "exclusif"]),
    status: "published",
    generatedBy: "manual",
    rating: "9.1",
  },
];

let inserted = 0;
for (const card of cards) {
  try {
    await conn.execute(
      `INSERT INTO seoCards (slug, title, subtitle, category, city, country, region, description, highlights, metaTitle, metaDescription, imageUrl, priceLevel, tags, status, generatedBy, rating, publishedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW())`,
      [card.slug, card.title, card.subtitle, card.category, card.city, card.country, card.region, card.description, card.highlights, card.metaTitle, card.metaDescription, card.imageUrl, card.priceLevel, card.tags, card.status, card.generatedBy, card.rating]
    );
    inserted++;
    console.log(`✓ ${card.title}`);
  } catch (e) {
    if (e.code === 'ER_DUP_ENTRY') {
      console.log(`⊘ ${card.title} (déjà existant)`);
    } else {
      console.error(`✗ ${card.title}:`, e.message);
    }
  }
}

console.log(`\n${inserted} fiches insérées sur ${cards.length}`);
await conn.end();
