CREATE TABLE `clientProfiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`pseudo` varchar(64),
	`mode` enum('signature','fantome') DEFAULT 'signature',
	`dietRegime` varchar(256),
	`dietAllergies` text,
	`dietOther` text,
	`travelStyles` text,
	`travelBudget` enum('economique','confort','premium','luxe','sans_limite') DEFAULT 'confort',
	`travelGroup` enum('solo','couple','famille','amis','business') DEFAULT 'couple',
	`travelMobility` enum('aucune','pmr','reduite','poussette') DEFAULT 'aucune',
	`languages` text,
	`pet` enum('aucun','chien','chat','autre') DEFAULT 'aucun',
	`smoking` enum('non_fumeur','fumeur','cigare','vape') DEFAULT 'non_fumeur',
	`dresscode` enum('casual','smart_casual','chic','formel') DEFAULT 'smart_casual',
	`ecofriendly` boolean DEFAULT false,
	`homeCity` varchar(128),
	`homeAddress` text,
	`preferredAirport` varchar(16),
	`airportLounge` boolean DEFAULT false,
	`priorityLane` boolean DEFAULT false,
	`clothingSize` varchar(16),
	`shoeSize` varchar(8),
	`favoriteAlcohol` varchar(128),
	`favoriteCuisine` varchar(256),
	`sleepPreference` varchar(128),
	`tempPreference` varchar(64),
	`freeNotes` text,
	`aiLastExtracted` timestamp,
	`aiExtractionCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clientProfiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `clientProfiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `companions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(128) NOT NULL,
	`relationship` enum('conjoint','enfant','parent','ami','collegue','autre') DEFAULT 'autre',
	`birthDate` varchar(10),
	`avatarUrl` text,
	`dietRegime` varchar(256),
	`dietAllergies` text,
	`dietOther` text,
	`travelStyles` text,
	`travelBudget` enum('economique','confort','premium','luxe','sans_limite') DEFAULT 'confort',
	`travelMobility` enum('aucune','pmr','reduite','poussette') DEFAULT 'aucune',
	`languages` text,
	`pet` enum('aucun','chien','chat','autre') DEFAULT 'aucun',
	`smoking` enum('non_fumeur','fumeur','cigare','vape') DEFAULT 'non_fumeur',
	`clothingSize` varchar(16),
	`shoeSize` varchar(8),
	`favoriteAlcohol` varchar(128),
	`favoriteCuisine` varchar(256),
	`freeNotes` text,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `companions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `destinationSaves` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`destinationId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `destinationSaves_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `userDestinations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(256) NOT NULL,
	`description` text,
	`coverImageUrl` text,
	`tags` text,
	`tripType` enum('leisure','business','romantic','family','staycation','adventure','wellness') DEFAULT 'leisure',
	`budget` enum('economique','confort','premium','luxe') DEFAULT 'confort',
	`duration` int,
	`destination` varchar(256),
	`country` varchar(128),
	`lat` float,
	`lng` float,
	`steps` text,
	`highlights` text,
	`tips` text,
	`visibility` enum('private','family','public') DEFAULT 'private',
	`isVerified` boolean DEFAULT false,
	`isFeatured` boolean DEFAULT false,
	`viewCount` int DEFAULT 0,
	`saveCount` int DEFAULT 0,
	`likeCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `userDestinations_id` PRIMARY KEY(`id`)
);
