-- Migration: Discount Offers (Offres avec Réductions Premium)
CREATE TABLE `discountOffers` (
  `id` int AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `slug` varchar(256) NOT NULL UNIQUE,
  `title` varchar(256) NOT NULL,
  `subtitle` varchar(512),
  `tagline` varchar(256),
  `establishmentId` int,
  `establishmentName` varchar(256) NOT NULL,
  `establishmentCategory` enum('hotel','villa','restaurant','spa','experience','transport','wellness','yacht','chalet') NOT NULL,
  `city` varchar(128) NOT NULL,
  `country` varchar(128) NOT NULL,
  `region` varchar(128),
  `lat` float,
  `lng` float,
  `isPremiumDestination` boolean NOT NULL DEFAULT true,
  `originalPricePerNight` int,
  `discountedPricePerNight` int,
  `originalPriceTotal` int,
  `discountedPriceTotal` int,
  `discountPercent` int,
  `currency` varchar(3) NOT NULL DEFAULT 'EUR',
  `packageType` enum('1_night','2_nights','3_nights','weekend','week','custom') NOT NULL DEFAULT '2_nights',
  `durationNights` int NOT NULL DEFAULT 2,
  `maxGuests` int DEFAULT 2,
  `priceTier` enum('tier1','tier2','tier3','tier4') NOT NULL,
  `sector` enum('hotelerie','gastronomie','experiences','villas','transport','bienetre','yachting','ski') NOT NULL,
  `heroImageUrl` text,
  `galleryImages` text,
  `coverImageUrl` text,
  `description` text NOT NULL,
  `shortDescription` varchar(500),
  `highlights` text,
  `included` text,
  `notIncluded` text,
  `conditions` text,
  `insiderTip` text,
  `availableFrom` timestamp,
  `availableTo` timestamp,
  `isFlashOffer` boolean NOT NULL DEFAULT false,
  `flashExpiresAt` timestamp,
  `totalSlots` int,
  `bookedSlots` int DEFAULT 0,
  `bookingUrl` text,
  `affiliateCode` varchar(128),
  `commissionPercent` decimal(5,2),
  `accessLevel` enum('free','premium_only') NOT NULL DEFAULT 'free',
  `status` enum('draft','published','expired','sold_out') NOT NULL DEFAULT 'draft',
  `isFeatured` boolean NOT NULL DEFAULT false,
  `sortOrder` int DEFAULT 0,
  `viewCount` int DEFAULT 0,
  `bookingCount` int DEFAULT 0,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `discountOfferSaves` (
  `id` int AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `userId` int NOT NULL,
  `offerId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
