-- Migration 0033: Content Pages (pages de contenu SEO generees)
CREATE TABLE IF NOT EXISTS `content_pages` (
  `id` int NOT NULL AUTO_INCREMENT,
  `slug` varchar(200) NOT NULL,
  `title` varchar(300) NOT NULL,
  `metaTitle` varchar(200),
  `metaDescription` varchar(320),
  `type` enum('guide','inspiration','parcours','evenement','secret') DEFAULT 'guide',
  `city` varchar(100) NOT NULL,
  `country` varchar(100) DEFAULT 'France',
  `category` varchar(50),
  `searchIntent` varchar(300),
  `heroImage` varchar(500),
  `introText` text,
  `content` longtext,
  `establishmentSlugs` json DEFAULT NULL,
  `season` enum('toute_annee','printemps','ete','automne','hiver') DEFAULT 'toute_annee',
  `isPublished` boolean DEFAULT TRUE,
  `viewCount` int DEFAULT 0,
  `saveCount` int DEFAULT 0,
  `seoIntelligenceId` int NULL,
  `generatedBy` enum('claude','manual','manus') DEFAULT 'claude',
  `verifiedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_slug` (`slug`),
  KEY `idx_city` (`city`),
  KEY `idx_type` (`type`)
);
