import mysql from 'mysql2/promise';

// Calcul des dates relatives (vendredi prochain, samedi, dimanche, etc.)
function nextWeekday(dayOfWeek) {
  const today = new Date();
  const current = today.getDay(); // 0=dim, 1=lun, ..., 6=sam
  let diff = dayOfWeek - current;
  if (diff <= 0) diff += 7;
  const d = new Date(today);
  d.setDate(today.getDate() + diff);
  return d.toISOString().split('T')[0];
}

const today = new Date().toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
const thursday = nextWeekday(4);  // jeudi
const friday = nextWeekday(5);    // vendredi
const saturday = nextWeekday(6);  // samedi
const sunday = nextWeekday(0);    // dimanche
const wednesday = nextWeekday(3); // mercredi

const events = [
  // ─── BORDEAUX ───────────────────────────────────────────────────────
  {
    title: "DJ Set House Session",
    description: "Une nuit électro avec vue panoramique sur la Garonne. DJs résidents + guest international. Cocktails signature dès 12€.",
    category: "soiree",
    venue_name: "Le Mama Rooftop",
    venue_address: "5 Quai des Chartrons, Bordeaux",
    city: "Bordeaux",
    lat: "44.8566",
    lng: "-0.5714",
    date: friday,
    time_start: "22:00",
    time_end: "04:00",
    price: "Gratuit avant minuit · 12€ après",
    dress_code: "Smart casual",
    image_url: null,
    booking_url: null,
    is_vip: true,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "Vernissage Lumières du Sud",
    description: "Exposition de photographies contemporaines sur la lumière méditerranéenne. Champagne offert à l'ouverture. Artiste invité : Léa Moreau.",
    category: "expo",
    venue_name: "Galerie des Chartrons",
    venue_address: "18 Rue Notre-Dame, Bordeaux",
    city: "Bordeaux",
    lat: "44.8570",
    lng: "-0.5720",
    date: thursday,
    time_start: "19:00",
    time_end: "22:00",
    price: "Entrée libre",
    dress_code: null,
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "Dégustation Verticale Saint-Émilion",
    description: "5 millésimes commentés par un sommelier. Cave voûtée du XVIIIe siècle. Accord mets-vins inclus. Arrivée conseillée 15min avant.",
    category: "degustation",
    venue_name: "Bar à Vin de Bordeaux",
    venue_address: "3 Cours du 30 Juillet, Bordeaux",
    city: "Bordeaux",
    lat: "44.8412",
    lng: "-0.5736",
    date: saturday,
    time_start: "20:30",
    time_end: "22:30",
    price: "35€/pers",
    dress_code: null,
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "Concert Jazz Quintet",
    description: "Soirée jazz avec le quintet bordelais Swing & Co. Répertoire standards américains et compositions originales. Bar ouvert.",
    category: "concert",
    venue_name: "Rock School Barbey",
    venue_address: "18 Cours Barbey, Bordeaux",
    city: "Bordeaux",
    lat: "44.8320",
    lng: "-0.5640",
    date: friday,
    time_start: "21:00",
    time_end: "23:30",
    price: "15€",
    dress_code: null,
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "Brunch DJ Dominical",
    description: "Brunch gastronomique avec DJ set ambiant. Buffet illimité, cocktails de brunch, piscine accessible. Réservation obligatoire.",
    category: "brunch",
    venue_name: "Les Bains de Léa",
    venue_address: "12 Rue des Bains, Bordeaux",
    city: "Bordeaux",
    lat: "44.8380",
    lng: "-0.5780",
    date: sunday,
    time_start: "11:00",
    time_end: "15:00",
    price: "42€/pers",
    dress_code: null,
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "After-Work Cocktails Premium",
    description: "Happy hour sur la terrasse avec vue sur la Garonne. Cocktails à 8€, planches charcuterie. Ambiance lounge, networking.",
    category: "afterwork",
    venue_name: "Le Symbiose",
    venue_address: "22 Quai de la Paludate, Bordeaux",
    city: "Bordeaux",
    lat: "44.8290",
    lng: "-0.5590",
    date: thursday,
    time_start: "18:30",
    time_end: "21:00",
    price: "Entrée libre",
    dress_code: null,
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "Nuit Électro sur la Garonne",
    description: "Soirée techno et house sur le bateau-club emblématique de Bordeaux. 3 scènes, 8 DJs. Ambiance underground chic.",
    category: "soiree",
    venue_name: "I.Boat",
    venue_address: "Quai Armand Lalande, Bordeaux",
    city: "Bordeaux",
    lat: "44.8650",
    lng: "-0.5820",
    date: saturday,
    time_start: "23:00",
    time_end: "06:00",
    price: "12€",
    dress_code: "Casual",
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "Soirée Salsa & Latin Vibes",
    description: "Cours de salsa débutants 21h-22h, puis soirée libre. Ambiance cubaine, mojitos, professeurs sur place. Tous niveaux bienvenus.",
    category: "soiree",
    venue_name: "Casa Latina",
    venue_address: "8 Rue du Palais Gallien, Bordeaux",
    city: "Bordeaux",
    lat: "44.8450",
    lng: "-0.5810",
    date: wednesday,
    time_start: "21:00",
    time_end: "01:00",
    price: "8€",
    dress_code: null,
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
  // ─── PARIS ──────────────────────────────────────────────────────────
  {
    title: "Vernissage Art Contemporain",
    description: "Ouverture de l'exposition 'Fragments' de l'artiste coréen Jae-Won Oh. Galerie internationale, champagne, rencontre avec l'artiste.",
    category: "expo",
    venue_name: "Galerie Perrotin",
    venue_address: "76 Rue de Turenne, Paris 3e",
    city: "Paris",
    lat: "48.8603",
    lng: "2.3621",
    date: thursday,
    time_start: "18:00",
    time_end: "21:00",
    price: "Entrée libre",
    dress_code: null,
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "DJ Set Rooftop Marais",
    description: "Soirée sur le rooftop le plus couru du Marais. Vue 360° sur Paris, DJ house & disco, cocktails signature. Arrivée avant 22h recommandée.",
    category: "soiree",
    venue_name: "Le Perchoir Marais",
    venue_address: "14 Rue Crespin du Gast, Paris 11e",
    city: "Paris",
    lat: "48.8633",
    lng: "2.3789",
    date: friday,
    time_start: "21:00",
    time_end: "02:00",
    price: "Gratuit (conso min 15€)",
    dress_code: "Smart casual",
    image_url: null,
    booking_url: null,
    is_vip: true,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "Concert Indie Rock",
    description: "Soirée indie avec 2 groupes en première partie + tête d'affiche. Salle mythique de Pigalle, son exceptionnel.",
    category: "concert",
    venue_name: "La Cigale",
    venue_address: "120 Boulevard Rochechouart, Paris 18e",
    city: "Paris",
    lat: "48.8842",
    lng: "2.3436",
    date: saturday,
    time_start: "20:00",
    time_end: "23:30",
    price: "28€",
    dress_code: null,
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "Dégustation Champagne Prestige",
    description: "Sélection de 6 champagnes grands crus commentés par le sommelier. Accord avec fromages affinés. Nombre de places limité à 12.",
    category: "degustation",
    venue_name: "Cave Legrand Filles & Fils",
    venue_address: "1 Rue de la Banque, Paris 2e",
    city: "Paris",
    lat: "48.8672",
    lng: "2.3418",
    date: thursday,
    time_start: "19:30",
    time_end: "21:30",
    price: "45€/pers",
    dress_code: null,
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "Dîner Secret — Lieu Révélé 2h Avant",
    description: "Table d'exception dans un lieu confidentiel du Paris caché. Chef étoilé, 8 convives max, menu dégustation 7 plats. Expérience unique.",
    category: "diner_secret",
    venue_name: "Lieu confidentiel Paris",
    venue_address: "Révélé 2h avant",
    city: "Paris",
    lat: "48.8566",
    lng: "2.3522",
    date: saturday,
    time_start: "20:00",
    time_end: "23:30",
    price: "85€/pers",
    dress_code: "Tenue de soirée",
    image_url: null,
    booking_url: null,
    is_vip: true,
    is_members_only: true,
    source: "baymora_seed",
  },
  {
    title: "Stand-Up Comedy — Soirée Spéciale",
    description: "3 comédiens + 1 tête d'affiche surprise. Ambiance club new-yorkais, 2 consommations incluses. Réservation fortement conseillée.",
    category: "spectacle",
    venue_name: "Le Comedy Club",
    venue_address: "42 Boulevard Bonne Nouvelle, Paris 10e",
    city: "Paris",
    lat: "48.8701",
    lng: "2.3508",
    date: friday,
    time_start: "20:30",
    time_end: "23:00",
    price: "18€",
    dress_code: null,
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
  {
    title: "After-Work Terrasse Canal",
    description: "Le spot after-work le plus cool de Paris. Terrasse au bord du canal, DJ ambiant, bières artisanales, street food. Gratuit, venir tôt.",
    category: "afterwork",
    venue_name: "Le Comptoir Général",
    venue_address: "80 Quai de Jemmapes, Paris 10e",
    city: "Paris",
    lat: "48.8712",
    lng: "2.3668",
    date: wednesday,
    time_start: "18:00",
    time_end: "22:00",
    price: "Entrée libre",
    dress_code: null,
    image_url: null,
    booking_url: null,
    is_vip: false,
    is_members_only: false,
    source: "baymora_seed",
  },
];

async function seed() {
  const conn = await mysql.createConnection(process.env.DATABASE_URL);
  try {
    // Vider les événements seed existants
    await conn.execute("DELETE FROM events WHERE source = 'baymora_seed'");
    
    for (const ev of events) {
      await conn.execute(
        `INSERT INTO events (title, description, category, venue_name, venue_address, city, lat, lng, date, time_start, time_end, price, dress_code, image_url, booking_url, is_vip, is_members_only, source)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [ev.title, ev.description, ev.category, ev.venue_name, ev.venue_address, ev.city,
         ev.lat, ev.lng, ev.date, ev.time_start, ev.time_end, ev.price, ev.dress_code,
         ev.image_url, ev.booking_url, ev.is_vip ? 1 : 0, ev.is_members_only ? 1 : 0, ev.source]
      );
    }
    console.log(`✓ ${events.length} événements seedés (Bordeaux + Paris)`);
  } finally {
    await conn.end();
  }
}

seed().catch(e => { console.error(e.message); process.exit(1); });
