import mysql from 'mysql2/promise';

const seedOffers = [
  {
    slug: 'hotel-de-paris-monaco-weekend',
    title: 'Hôtel de Paris Monte-Carlo',
    subtitle: 'Suite Deluxe avec vue mer — Weekend d\'exception',
    tagline: 'L\'adresse mythique de la Principauté',
    establishmentName: 'Hôtel de Paris Monte-Carlo',
    establishmentCategory: 'hotel',
    city: 'Monaco', country: 'Monaco', region: 'Côte d\'Azur',
    lat: 43.7396, lng: 7.4278,
    originalPricePerNight: 2800, discountedPricePerNight: 1960,
    originalPriceTotal: 5600, discountedPriceTotal: 3920,
    discountPercent: 30, currency: 'EUR',
    packageType: 'weekend', durationNights: 2, maxGuests: 2,
    priceTier: 'tier3', sector: 'hotelerie',
    heroImageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1600&q=90',
    description: 'Symbole absolu du luxe monégasque depuis 1864, l\'Hôtel de Paris incarne l\'excellence à la française sur la Place du Casino. Ses suites offrent une vue imprenable sur la Méditerranée et les jardins princiers. Le package inclut le petit-déjeuner au Louis XV d\'Alain Ducasse, accès au spa Thermes Marins Monte-Carlo et service de conciergerie 24h/24.',
    shortDescription: 'Suite Deluxe vue mer, petit-déjeuner Ducasse, spa Thermes Marins inclus.',
    highlights: JSON.stringify(['Vue panoramique sur la Méditerranée','Petit-déjeuner au Louis XV d\'Alain Ducasse','Accès spa Thermes Marins Monte-Carlo','Service conciergerie 24h/24','Parking voiturier inclus']),
    included: JSON.stringify(['2 nuits en Suite Deluxe','Petit-déjeuner gastronomique x2','Accès spa illimité','Bouteille de champagne à l\'arrivée','Late check-out 14h']),
    insiderTip: 'Demandez la Suite Méditerranée au 5ème étage — la vue sur le port de Monaco au coucher du soleil est à couper le souffle.',
    accessLevel: 'free', status: 'published', isFeatured: 1, isFlashOffer: 0, sortOrder: 10,
  },
  {
    slug: 'villa-saint-tropez-semaine',
    title: 'Villa Privée Saint-Tropez',
    subtitle: 'Villa 5 chambres avec piscine à débordement — Semaine prestige',
    tagline: 'L\'art de vivre tropézien dans votre villa privée',
    establishmentName: 'Villa Les Palmiers',
    establishmentCategory: 'villa',
    city: 'Saint-Tropez', country: 'France', region: 'Provence-Alpes-Côte d\'Azur',
    lat: 43.2677, lng: 6.6402,
    originalPriceTotal: 35000, discountedPriceTotal: 24500,
    originalPricePerNight: 5000, discountedPricePerNight: 3500,
    discountPercent: 30, currency: 'EUR',
    packageType: 'week', durationNights: 7, maxGuests: 10,
    priceTier: 'tier4', sector: 'villas',
    heroImageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1600&q=90',
    description: 'Nichée dans les hauteurs de Saint-Tropez avec vue à 180° sur la baie, cette villa d\'exception de 600m² dispose de 5 suites, d\'une piscine à débordement chauffée, d\'un chef privé sur demande et d\'un accès direct à la plage de Pampelonne.',
    shortDescription: 'Villa 600m², 5 suites, piscine à débordement, vue mer 180°, chef privé disponible.',
    highlights: JSON.stringify(['Vue panoramique 180° sur la baie','Piscine à débordement chauffée','5 suites avec salle de bain privative','Chef privé sur demande','Accès plage de Pampelonne']),
    included: JSON.stringify(['7 nuits en villa privée','Service de ménage quotidien','Voiturier','Accueil champagne','Conciergerie Baymora dédiée']),
    insiderTip: 'Réservez le chef privé dès l\'arrivée pour un dîner sur la terrasse au coucher du soleil.',
    accessLevel: 'free', status: 'published', isFeatured: 1, isFlashOffer: 0, sortOrder: 9,
  },
  {
    slug: 'le-bristol-paris-suite',
    title: 'Le Bristol Paris',
    subtitle: 'Suite Royale — 3 nuits au cœur du Triangle d\'Or',
    tagline: 'Le palace parisien par excellence',
    establishmentName: 'Le Bristol Paris',
    establishmentCategory: 'hotel',
    city: 'Paris', country: 'France', region: 'Île-de-France',
    lat: 48.8706, lng: 2.3116,
    originalPricePerNight: 3500, discountedPricePerNight: 2450,
    originalPriceTotal: 10500, discountedPriceTotal: 7350,
    discountPercent: 30, currency: 'EUR',
    packageType: '3_nights', durationNights: 3, maxGuests: 2,
    priceTier: 'tier4', sector: 'hotelerie',
    heroImageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1600&q=90',
    description: 'Érigé en 1925 rue du Faubourg Saint-Honoré, Le Bristol Paris est le seul palace parisien à posséder une piscine en plein air. La Suite Royale de 200m² offre une vue imprenable sur les toits de Paris et les jardins intérieurs.',
    shortDescription: 'Suite Royale 200m², Epicure 3 étoiles, spa Sisley, shopping privé inclus.',
    highlights: JSON.stringify(['Suite Royale 200m² vue jardins','Petit-déjeuner Epicure 3 étoiles Michelin','Accès spa Sisley Paris','Piscine en plein air','Service shopping privé rue du Faubourg']),
    included: JSON.stringify(['3 nuits en Suite Royale','Petit-déjeuner gastronomique x3','Accès spa illimité','Transfert aéroport en berline','Bouteille de Krug à l\'arrivée']),
    insiderTip: 'Demandez une table au jardin pour le brunch du dimanche.',
    accessLevel: 'free', status: 'published', isFeatured: 1, isFlashOffer: 0, sortOrder: 8,
  },
  {
    slug: 'four-seasons-george-v-paris',
    title: 'Four Seasons George V Paris',
    subtitle: 'Chambre Supérieure — 2 nuits avec dîner au Cinq',
    tagline: 'L\'avenue George V, l\'adresse de légende',
    establishmentName: 'Four Seasons Hotel George V',
    establishmentCategory: 'hotel',
    city: 'Paris', country: 'France', region: 'Île-de-France',
    lat: 48.8698, lng: 2.3025,
    originalPricePerNight: 1800, discountedPricePerNight: 1260,
    originalPriceTotal: 3600, discountedPriceTotal: 2520,
    discountPercent: 30, currency: 'EUR',
    packageType: '2_nights', durationNights: 2, maxGuests: 2,
    priceTier: 'tier3', sector: 'hotelerie',
    heroImageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1600&q=90',
    description: 'Inauguré en 1928 sur l\'avenue George V, ce palace iconique est célèbre pour ses compositions florales spectaculaires et son restaurant Le Cinq (3 étoiles Michelin).',
    shortDescription: '2 nuits, dîner au Cinq 3 étoiles, spa, conciergerie Paris inclus.',
    highlights: JSON.stringify(['Dîner gastronomique au Cinq 3 étoiles','Compositions florales iconiques','Spa avec piscine intérieure','Vue sur cour intérieure','Accès VIP galeries d\'art']),
    included: JSON.stringify(['2 nuits en Chambre Supérieure','Petit-déjeuner continental x2','Dîner au Cinq pour 2 personnes','Accès spa','Bouteille de champagne']),
    insiderTip: 'Les arrangements floraux changent chaque semaine — demandez à rencontrer Jeff Leatham.',
    accessLevel: 'free', status: 'published', isFeatured: 0, isFlashOffer: 1, sortOrder: 7,
  },
  {
    slug: 'burj-al-arab-dubai-suite',
    title: 'Burj Al Arab Jumeirah',
    subtitle: 'Suite Deluxe — 2 nuits dans l\'hôtel le plus luxueux du monde',
    tagline: 'L\'icône de Dubai, votre suite dans les nuages',
    establishmentName: 'Burj Al Arab Jumeirah',
    establishmentCategory: 'hotel',
    city: 'Dubai', country: 'Émirats Arabes Unis', region: 'Dubai',
    lat: 25.1412, lng: 55.1853,
    originalPricePerNight: 4500, discountedPricePerNight: 3150,
    originalPriceTotal: 9000, discountedPriceTotal: 6300,
    discountPercent: 30, currency: 'EUR',
    packageType: '2_nights', durationNights: 2, maxGuests: 2,
    priceTier: 'tier4', sector: 'hotelerie',
    heroImageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1600&q=90',
    description: 'Érigé sur une île artificielle en forme de voile, le Burj Al Arab est le symbole absolu du luxe à Dubai. Chaque suite duplex de 170m² minimum dispose d\'un majordome privé 24h/24.',
    shortDescription: 'Suite duplex 170m², majordome privé, transfert Rolls-Royce, dîner Al Muntaha.',
    highlights: JSON.stringify(['Suite duplex 170m² minimum','Majordome privé 24h/24','Transfert en Rolls-Royce ou hélicoptère','Dîner au Al Muntaha 27ème étage','Beach club privé exclusif']),
    included: JSON.stringify(['2 nuits en Suite Deluxe','Petit-déjeuner gastronomique x2','Transfert aéroport Rolls-Royce','Dîner Al Muntaha pour 2','Accès beach club']),
    insiderTip: 'Réservez l\'hélicoptère pour l\'arrivée — atterrir sur le hélipad est unique au monde.',
    accessLevel: 'free', status: 'published', isFeatured: 1, isFlashOffer: 0, sortOrder: 6,
  },
  {
    slug: 'experience-gastronomique-monaco',
    title: 'Louis XV — Alain Ducasse à Monaco',
    subtitle: 'Dîner privé pour 2 + suite au Métropole — Package Prestige',
    tagline: 'La table des tables sur la Côte d\'Azur',
    establishmentName: 'Le Louis XV — Alain Ducasse',
    establishmentCategory: 'restaurant',
    city: 'Monaco', country: 'Monaco', region: 'Côte d\'Azur',
    lat: 43.7396, lng: 7.4278,
    originalPriceTotal: 2800, discountedPriceTotal: 1960,
    discountPercent: 30, currency: 'EUR',
    packageType: '1_night', durationNights: 1, maxGuests: 2,
    priceTier: 'tier3', sector: 'gastronomie',
    heroImageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1600&q=90',
    description: 'Le Louis XV d\'Alain Ducasse à l\'Hôtel de Paris est la table la plus mythique de la Méditerranée. 3 étoiles Michelin depuis 1990.',
    shortDescription: 'Dîner 3 étoiles Michelin pour 2, accord vins, suite Métropole, berline privée.',
    highlights: JSON.stringify(['3 étoiles Michelin depuis 1990','Menu dégustation 8 services','Cave à vins exceptionnelle','Nuit en suite au Métropole','Vue sur la Place du Casino']),
    included: JSON.stringify(['Dîner gastronomique 8 services pour 2','Accord mets-vins','1 nuit en suite Métropole','Transfert berline privée','Champagne de bienvenue']),
    insiderTip: 'Demandez la table 12 — vue directe sur les jardins et la mer.',
    accessLevel: 'free', status: 'published', isFeatured: 1, isFlashOffer: 0, sortOrder: 5,
  },
  {
    slug: 'spa-cheval-blanc-paris',
    title: 'Spa Cheval Blanc Paris',
    subtitle: 'Journée Spa Prestige — Soins signature + déjeuner gastronomique',
    tagline: 'Le spa le plus exclusif de Paris',
    establishmentName: 'Spa Cheval Blanc Paris',
    establishmentCategory: 'spa',
    city: 'Paris', country: 'France', region: 'Île-de-France',
    lat: 48.8566, lng: 2.3522,
    originalPriceTotal: 1200, discountedPriceTotal: 840,
    discountPercent: 30, currency: 'EUR',
    packageType: '1_night', durationNights: 1, maxGuests: 2,
    priceTier: 'tier2', sector: 'bienetre',
    heroImageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1600&q=90',
    description: 'Niché au cœur du Cheval Blanc Paris (palace LVMH), le spa Guerlain de 1400m² est considéré comme le plus beau spa de Paris.',
    shortDescription: 'Soin Guerlain 90min, piscine 25m, accès aquatique, déjeuner Limbar inclus.',
    highlights: JSON.stringify(['Spa Guerlain 1400m²','Piscine intérieure 25m','Soin signature 90 minutes','Déjeuner au Limbar','Vue sur la Seine']),
    included: JSON.stringify(['Soin signature Guerlain 90min','Accès spa illimité','Déjeuner au Limbar pour 2','Peignoir et chaussons','Produits Guerlain offerts']),
    insiderTip: 'Arrivez à 10h pour profiter de la piscine avant l\'affluence.',
    accessLevel: 'free', status: 'published', isFeatured: 0, isFlashOffer: 0, sortOrder: 4,
  },
  {
    slug: 'yacht-cannes-journee',
    title: 'Yacht Privé — Côte d\'Azur',
    subtitle: 'Journée en mer de Cannes à Monaco — Yacht 24m avec équipage',
    tagline: 'La Méditerranée comme terrain de jeu',
    establishmentName: 'Baymora Yachting',
    establishmentCategory: 'yacht',
    city: 'Cannes', country: 'France', region: 'Provence-Alpes-Côte d\'Azur',
    lat: 43.5528, lng: 7.0174,
    originalPriceTotal: 8500, discountedPriceTotal: 5950,
    discountPercent: 30, currency: 'EUR',
    packageType: '1_night', durationNights: 1, maxGuests: 8,
    priceTier: 'tier4', sector: 'yachting',
    heroImageUrl: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=1600&q=90',
    description: 'Embarquez pour une journée inoubliable à bord d\'un yacht de 24m avec équipage complet. Départ de Cannes, escale aux Îles de Lérins.',
    shortDescription: 'Yacht 24m, équipage 3 personnes, déjeuner à bord, Cannes-Monaco, criques secrètes.',
    highlights: JSON.stringify(['Yacht 24m avec équipage complet','Déjeuner gastronomique à bord','Criques secrètes et baignade','Itinéraire Cannes-Monaco','Champagne et open bar']),
    included: JSON.stringify(['Journée complète (10h-20h)','Équipage 3 personnes','Déjeuner gastronomique','Open bar champagne et vins','Équipements nautiques']),
    insiderTip: 'Demandez à stopper à la Calanque de l\'Esterel au coucher du soleil.',
    accessLevel: 'free', status: 'published', isFeatured: 1, isFlashOffer: 0, sortOrder: 3,
  },
  {
    slug: 'chalet-courchevel-1850-ski',
    title: 'Chalet Privé Courchevel 1850',
    subtitle: 'Chalet 6 chambres — Semaine ski prestige avec chef et spa',
    tagline: 'Le sommet du ski de luxe dans les Alpes',
    establishmentName: 'Chalet Les Neiges Éternelles',
    establishmentCategory: 'chalet',
    city: 'Courchevel', country: 'France', region: 'Savoie',
    lat: 45.4152, lng: 6.6337,
    originalPriceTotal: 42000, discountedPriceTotal: 29400,
    originalPricePerNight: 6000, discountedPricePerNight: 4200,
    discountPercent: 30, currency: 'EUR',
    packageType: 'week', durationNights: 7, maxGuests: 12,
    priceTier: 'tier4', sector: 'ski',
    heroImageUrl: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?w=1600&q=90',
    description: 'Au cœur de Courchevel 1850, station la plus exclusive des Alpes, ce chalet de 700m² dispose de 6 suites avec vue sur les pistes.',
    shortDescription: 'Chalet 700m², ski-in/ski-out, chef étoilé, spa, moniteur privé, 6 suites.',
    highlights: JSON.stringify(['Ski-in/ski-out direct sur les pistes','Chef étoilé résidentiel','Spa avec hammam et sauna','Moniteur de ski privé','Cave à vins 500 bouteilles']),
    included: JSON.stringify(['7 nuits en chalet privé','Chef étoilé 3 repas/jour','Spa et bien-être illimité','Moniteur ski 5 jours','Transfert aéroport en hélicoptère']),
    insiderTip: 'Réservez une sortie hors-piste vers la Combe de la Saulire — inaccessible sans guide.',
    accessLevel: 'free', status: 'published', isFeatured: 1, isFlashOffer: 0, sortOrder: 2,
  },
  {
    slug: 'experience-bali-villa-ubud',
    title: 'Villa Privée Ubud — Bali',
    subtitle: 'Villa avec piscine à débordement sur jungle — 5 nuits retraite',
    tagline: 'La sérénité absolue au cœur de la jungle balinaise',
    establishmentName: 'Villa Karma Kandara Ubud',
    establishmentCategory: 'villa',
    city: 'Ubud', country: 'Indonésie', region: 'Bali',
    lat: -8.5069, lng: 115.2625,
    originalPricePerNight: 1200, discountedPricePerNight: 840,
    originalPriceTotal: 6000, discountedPriceTotal: 4200,
    discountPercent: 30, currency: 'EUR',
    packageType: 'custom', durationNights: 5, maxGuests: 4,
    priceTier: 'tier2', sector: 'villas',
    heroImageUrl: 'https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=1600&q=90',
    description: 'Perchée au-dessus de la vallée de l\'Ayung à Ubud, cette villa de 3 pavillons dispose d\'une piscine à débordement avec vue sur la jungle tropicale.',
    shortDescription: '3 pavillons, piscine jungle, yoga quotidien, massages, cuisine végétarienne gastronomique.',
    highlights: JSON.stringify(['Piscine à débordement vue jungle','Cours de yoga quotidiens','Massages balinais inclus','Cuisine végétarienne gastronomique','Excursions culturelles privées']),
    included: JSON.stringify(['5 nuits en villa privée','Petits-déjeuners et dîners','Cours de yoga x5','Massages x5','Excursion temple et rizières']),
    insiderTip: 'Réveillez-vous à 5h30 pour le yoga au lever du soleil — la brume matinale sur la jungle est magique.',
    accessLevel: 'free', status: 'published', isFeatured: 0, isFlashOffer: 1, sortOrder: 1,
  },
];

async function run() {
  const conn = await mysql.createConnection(process.env.DATABASE_URL);
  let inserted = 0;
  for (const offer of seedOffers) {
    const cols = Object.keys(offer).join(', ');
    const placeholders = Object.keys(offer).map(() => '?').join(', ');
    const vals = Object.values(offer);
    try {
      await conn.execute(`INSERT INTO discountOffers (${cols}) VALUES (${placeholders})`, vals);
      inserted++;
      console.log(`✓ Inserted: ${offer.title}`);
    } catch (e) {
      if (e.code === 'ER_DUP_ENTRY') {
        console.log(`⚠ Already exists: ${offer.slug}`);
      } else {
        console.error(`✗ Error for ${offer.slug}:`, e.message);
      }
    }
  }
  await conn.end();
  console.log(`\nDone: ${inserted} offers inserted`);
}

run().catch(console.error);
